--Dimensions
CREATE TABLE DIM_TEST_RESULT(
	ResultKey	INT IDENTITY(1,1) PRIMARY KEY,
	ReportID	INT NOT NULL,
	TestType	VARCHAR(100) NOT NULL,
	TestDescription VARCHAR(255) NOT NULL,
	TestPrice DECIMAL(10, 2) NOT NULL,
	TestResultDiagnose VARCHAR(100) NOT NULL);

CREATE TABLE DIM_APPOINTED_DOCTOR(
	AppointedDoctorKey INT IDENTITY(1,1) PRIMARY KEY,
	AppointmentID INT NOT NULL,
	AppointedDoctorName VARCHAR(65) NOT NULL,
	DoctorDepartmentName VARCHAR(100) NOT NULL);

CREATE TABLE DIM_MEDICINE(
	MedicineKey INT IDENTITY(1,1) PRIMARY KEY,
	MedicineID INT NOT NULL,
	MedicineName VARCHAR(100) NOT NULL,
	MedicineType VARCHAR(100) NOT NULL,
	MedicineDescription VARCHAR(255) NOT NULL,
	MedicineCostOfGoodSold DECIMAL(10, 2) NOT NULL,
	MedicineSalePrice DECIMAL(10, 2) NOT NULL,
	MedicineSupplierName VARCHAR(100) NOT NULL,
	MedicineSupplierState VARCHAR(100) NOT NULL);

CREATE TABLE DIM_CALENDAR(
	CalendarKey INT IDENTITY(1,1) PRIMARY KEY,
	FullDate DATE NOT NULL,
	DayOfWeek VARCHAR(15) NOT NULL,
	DayOfMonth INT NOT NULL,
	Month VARCHAR(15) NOT NULL,
	Quarter INT NOT NULL,
	Year INT NOT NULL);

--Fact
CREATE TABLE FACT_SALE_TRANSACTION(
	ResultKey INT NOT NULL,
	AppointedDoctorKey INT NOT NULL,
	MedicineKey INT NOT NULL,
	CalendarKey INT NOT NULL,
	UnitsSold INT NOT NULL,
	DollarSold DECIMAL(10, 2) NOT NULL,
	CostOfGoodSold DECIMAL(10, 2) NOT NULL,
	CONSTRAINT PK_FACT PRIMARY KEY (ResultKey, AppointedDoctorKey, MedicineKey, CalendarKey),
	CONSTRAINT FK_FACT_RESULT FOREIGN KEY (ResultKey) REFERENCES DIM_TEST_RESULT(ResultKey),
	CONSTRAINT FK_FACT_DOCTOR FOREIGN KEY (AppointedDoctorKey) REFERENCES DIM_APPOINTED_DOCTOR(AppointedDoctorKey),
	CONSTRAINT FK_FACT_MEDICINE FOREIGN KEY (MedicineKey) REFERENCES DIM_MEDICINE(MedicineKey),
	CONSTRAINT FK_FACT_CALENDAR FOREIGN KEY (CalendarKey) REFERENCES DIM_CALENDAR(CalendarKey));
