-- Truncate and Execute SQL Tasks
ALTER TABLE FACT_SALE_TRANSACTION
DROP CONSTRAINT FK_FACT_CALENDAR;

ALTER TABLE FACT_SALE_TRANSACTION
DROP CONSTRAINT FK_FACT_DOCTOR;

ALTER TABLE FACT_SALE_TRANSACTION
DROP CONSTRAINT FK_FACT_MEDICINE;

ALTER TABLE FACT_SALE_TRANSACTION
DROP CONSTRAINT FK_FACT_RESULT;


TRUNCATE TABLE DIM_APPOINTED_DOCTOR;
TRUNCATE TABLE DIM_CALENDAR;
TRUNCATE TABLE DIM_MEDICINE;
TRUNCATE TABLE DIM_TEST_RESULT;
TRUNCATE TABLE FACT_SALE_TRANSACTION;

ALTER TABLE FACT_SALE_TRANSACTION
ADD CONSTRAINT FK_FACT_RESULT FOREIGN KEY (ResultKey) REFERENCES DIM_TEST_RESULT (ResultKey);

ALTER TABLE FACT_SALE_TRANSACTION
ADD CONSTRAINT FK_FACT_DOCTOR FOREIGN KEY (AppointedDoctorKey) REFERENCES DIM_APPOINTED_DOCTOR (AppointedDoctorKey);

ALTER TABLE FACT_SALE_TRANSACTION
ADD CONSTRAINT FK_FACT_MEDICINE FOREIGN KEY (MedicineKey) REFERENCES DIM_MEDICINE(MedicineKey);

ALTER TABLE   FACT_SALE_TRANSACTION
ADD CONSTRAINT FK_FACT_CALENDAR FOREIGN KEY (CalendarKey) REFERENCES DIM_CALENDAR(CalendarKey);


-- DIM_TEST_RESULT ETL
SELECT
	PD.ReportID,
	PD.TestResultDiagnose,
	T.TestType,
	T.TestDescription,
	T.TestPrice
FROM PATIENT_REPORTED AS PD
JOIN TEST AS T ON T.TestID = PD.TestID


-- DIM_APPOINTED_DOCTOR_ETL
SELECT
  A.AppointmentID,
  D.FirstName + ' ' + D.LastName AS AppointedDoctorName,
  DEP.DepartmentName AS DoctorDepartmentName
FROM
  APPOINTMENT AS A
  JOIN DOCTOR AS D ON D.DoctorID = A.DoctorID
  JOIN DEPARTMENT AS DEP ON DEP.DepartmentID = D.DepartmentID;

-- DIM_MEDICINE_ETL
SELECT
	M.MedicineID,
	M.MedicineName,
	M.MedicineType,
	M.MedicineDescription,
	M.MedicineCost AS MedicineCostOfGoodSolds,
	M.MedicineSalePrice,
	S.SupplierName AS MedicineSupplierName,
	S.ZIP AS MedicineSupplierZIP
FROM MEDICINE AS M
JOIN SUPPLIER AS S ON S.SupplierID = M.SupplierID

-- DIM_CALENDAR_ETL
SELECT DISTINCT
ReportDate AS FullDate,
	DATENAME(WEEKDAY, ReportDate) AS DayOfWeek,
	DATEPART(DAY, ReportDate) AS DayOfMonth,
	DATENAME(MONTH, ReportDate) AS Month,
	DATEPART(QUARTER, ReportDate) AS Quarter,
	DATENAME(YEAR, ReportDate) AS Year
FROM PATIENT_REPORT

-- FACT_ETL
SELECT 
	DW_RESULT.ResultKey,
	DW_APPOINTED_DOCTOR.AppointedDoctorKey,
	DW_MEDICINE.MedicineKey,
	DW_CALENDAR.CalendarKey,
	DB_MEDICINE_ORDER.Quantity AS UnitSold,
	DB_MEDICINE_ORDER.Quantity * DW_MEDICINE.MedicineSalePrice AS DollarSold,
	DW_MEDICINE.MedicineCostOfGoodSold
FROM MedicineSale_DW.dbo.DIM_MEDICINE AS DW_MEDICINE
JOIN WSHospital_DB.dbo.MEDICINE_ORDER AS DB_MEDICINE_ORDER
	ON DB_MEDICINE_ORDER.MedicineID = DW_MEDICINE.MedicineID
JOIN WSHospital_DB.dbo.PATIENT_REPORTED AS DB_PATIENT_REPORTED
	ON DB_PATIENT_REPORTED.ReportID = DB_MEDICINE_ORDER.ReportID
JOIN MedicineSale_DW.dbo.DIM_TEST_RESULT AS DW_RESULT
	ON DW_RESULT.ReportID = DB_PATIENT_REPORTED.ReportID
JOIN MedicineSale_DW.dbo.DIM_APPOINTED_DOCTOR AS DW_APPOINTED_DOCTOR
	ON DW_APPOINTED_DOCTOR.AppointmentID = DB_PATIENT_REPORTED.AppointmentID
JOIN MedicineSale_DW.dbo.DIM_CALENDAR AS DW_CALENDAR
	ON DW_CALENDAR.FullDate = DB_PATIENT_REPORTED.ReportDate;


--Testing DW Dimensions and Fact after ETLs
SELECT * FROM DIM_APPOINTED_DOCTOR;
SELECT * FROM DIM_MEDICINE;
SELECT * FROM DIM_CALENDAR;
SELECT * FROM DIM_TEST_RESULT;
SELECT * FROM FACT_SALE_TRANSACTION;
