--WS Project - Creating Operational Database
![Database ERD - WS Hospital](https://github.com/VinhhDo/VinhDo.github.io/assets/98499217/d1cf48cb-97d0-4217-a4a3-7f67a45ddadd)


--Parent Tables (Table without foreign key)
DROP 
  TABLE if exists DEPARTMENT;
CREATE TABLE DEPARTMENT (
  DepartmentID INT PRIMARY KEY, 
  DepartmentName VARCHAR(100), 
  );
DROP 
  TABLE if exists SUPPLIER;
CREATE TABLE SUPPLIER (
  SupplierID INT PRIMARY KEY, 
  SupplierName VARCHAR(100), 
  SupplierPhone VARCHAR(20), 
  SupplierCity VARCHAR(100), 
  SupplierState VARCHAR(100), 
  ZIP CHAR(6)
);
DROP 
  TABLE if exists TEST;
CREATE TABLE TEST (
  TestID INT IDENTITY(1, 1) PRIMARY KEY, 
  TestType VARCHAR(100), 
  TestDescription VARCHAR(255), 
  TestPrice DECIMAL(10, 2)
);
DROP 
  TABLE if exists PATIENT;
CREATE TABLE PATIENT (
  PatientID INT PRIMARY KEY, 
  FirstName VARCHAR(30), 
  LastName VARCHAR(30), 
  DOB DATE, 
  PhoneNumber VARCHAR(20), 
  Address VARCHAR(100), 
  City VARCHAR(100), 
  State VARCHAR(100), 
  ZIP VARCHAR(10), 
  Weight DECIMAL(10, 2), 
  Height DECIMAL(10, 2), 
  Temperature DECIMAL(5, 2), 
  BloodPressure VARCHAR(20)
);
-- Children tables (Table with foreign key)
DROP 
  TABLE if exists DOCTOR;
CREATE TABLE DOCTOR (
  DoctorID INT PRIMARY KEY, 
  FirstName VARCHAR(30), 
  LastName VARCHAR(30), 
  Education VARCHAR(100), 
  Salary DECIMAL(10, 2), 
  EmploymentStarted DATE, 
  EmploymentEnd DATE, 
  DepartmentID INT, 
  CONSTRAINT FK_DOCTOR_DEPARTMENT FOREIGN KEY (DepartmentID) REFERENCES DEPARTMENT(DepartmentID)
);
DROP 
  TABLE if exists APPOINTMENT;
CREATE TABLE APPOINTMENT (
  AppointmentID INT IDENTITY(1, 1) PRIMARY KEY, 
  AppointmentType VARCHAR(50), 
  Date DATE, 
  PatientID INT, 
  DoctorID INT, 
  CONSTRAINT FK_APPOINTMENT_PATIENT FOREIGN KEY (PatientID) REFERENCES PATIENT(PatientID), 
  CONSTRAINT FK_APPOINTMENT_DOCTOR FOREIGN KEY (DoctorID) REFERENCES DOCTOR(DoctorID)
);
DROP 
  TABLE if exists PATIENT_REPORT;
CREATE TABLE PATIENT_REPORT (
  ReportID INT IDENTITY(1, 1) PRIMARY KEY, 
  AppointmentID INT, 
  ReportDate DATE, 
  TestID INT, 
  TestResultDiagnose VARCHAR(100), 
  FOREIGN KEY (AppointmentID) REFERENCES APPOINTMENT(AppointmentID), 
  FOREIGN KEY (TestID) REFERENCES TEST(TestID)
);
DROP 
  TABLE if exists MEDICINE;
CREATE TABLE MEDICINE (
  MedicineID INT PRIMARY KEY, 
  MedicineName VARCHAR(100), 
  MedicineType VARCHAR(100), 
  MedicineDescription VARCHAR(255), 
  MedicineCost DECIMAL(10, 2), 
  MedicineSalePrice DECIMAL(10, 2), 
  SupplierID INT, 
  CONSTRAINT FK_MEDICINE_SUPPLIER FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID)
);
DROP 
  TABLE if exists MEDICINE_ORDER;
CREATE TABLE MEDICINE_ORDER(
  ReportID INT, 
  MedicineID INT, 
  Quantity INT, 
  CONSTRAINT PK_PRESCRIBED_MEDICINE PRIMARY KEY (ReportID, MedicineID), 
  CONSTRAINT FK_PRESCRIBED_MEDICINE_REPORT FOREIGN KEY (ReportID) REFERENCES PATIENT_REPORT(ReportID), 
  CONSTRAINT FK_PRESCRIBED_MEDICINE_ORDER_MEDICINE FOREIGN KEY (MedicineID) REFERENCES MEDICINE(MedicineID)
);
DROP 
  TABLE if exists EQUIPMENT;
CREATE TABLE EQUIPMENT (
  EquipmentID INT PRIMARY KEY, 
  EquipmentName VARCHAR(100), 
  EquipmentType VARCHAR(100), 
  EquipmentDescription VARCHAR(255), 
  EquipmentCost DECIMAL(10, 2), 
  SupplierID INT, 
  CONSTRAINT FK_EQUIPMENT_SUPPLIER FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID)
);
DROP 
  TABLE if exists EQUIPMENT_ORDER;
CREATE TABLE EQUIPMENT_ORDER (
  ReportID INT, 
  EquipmentID INT, 
  Quantity INT, 
  CONSTRAINT PK_PRESCRIBED_EQUIPMENT PRIMARY KEY (ReportID, EquipmentID), 
  CONSTRAINT FK_PRESCRIBED_EQUIPMENT_REPORT FOREIGN KEY (ReportID) REFERENCES PATIENT_REPORT(ReportID), 
  CONSTRAINT FK_PRESCRIBED_EQUIPMENT_ORDER_EQUIPMENT FOREIGN KEY (EquipmentID) REFERENCES EQUIPMENT(EquipmentID)
);
-- STAY TABLES
DROP 
  TABLE if exists NURSE;
CREATE TABLE NURSE (
  NurseID INT PRIMARY KEY, 
  FirstName VARCHAR(30), 
  LastName VARCHAR(30), 
  Education VARCHAR(100), 
  Salary DECIMAL(10, 2), 
  EmploymentStarted DATE, 
  EmploymentEnd DATE, 
  DepartmentID INT, 
  CONSTRAINT FK_NURSE_DEPARTMENT FOREIGN KEY (DepartmentID) REFERENCES DEPARTMENT(DepartmentID)
);
DROP 
  TABLE if exists ROOM;
CREATE TABLE ROOM (
  RoomID INT PRIMARY KEY, 
  Type VARCHAR(100), 
  Price DECIMAL(10, 2), 
  AreaID INT, 
  CONSTRAINT FK_ROOM_AREA FOREIGN KEY (AreaID) REFERENCES AREA(AreaID)
);
DROP 
  TABLE if exists STAY;
CREATE TABLE STAY (
  StayID INT IDENTITY(1, 1) PRIMARY KEY, 
  ReportID INT, 
  NurseID, 
  RoomID INT, 
  BeginDate DATE, 
  EndDate DATE, 
  TotalDays INT, 
  CONSTRAINT FK_STAY_NURSE FOREIGN KEY (NurseID) REFERENCES NURSE(NurseID), 
  CONSTRAINT FK_STAY_REPORT FOREIGN KEY (ReportID) REFERENCES PATIENT_REPORT(ReportID), 
  CONSTRAINT FK_STAY_ROOM FOREIGN KEY (RoomID) REFERENCES ROOM(RoomID)
);
